### ISSUE TITLE
Bolt 4 Filter / Query Search With Number Types Treated as Text

### ISSUE THREAD

**Issue by harrigo** [bolt/core#2620]
Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4
| Install type                   |  Composer install
| PHP version                 | 7.3
| Web server                  | Apache

Reproduction
------------

### Bug summary
I am using query search to filter by price. Works great with a URL like below on a list page:

`?price=>100000`

Price is a number field and I have filled out some entries with value over 1 million however strangely when I query for over (or under) 1 million I seem to just get no results.

`?price=>1000000`

### Specifics
So entity with number field type, have tried both number and text however same result. Filled out with prices. Prices can go over £1,000,000. Content type with query_search enabled and querying the listing page with POST params like above.

### Steps to reproduce

1. Create content_type with number type field e.g. price.
2. Create records, atleast one must have a value above 1000000
3. Go to list page and filter by that field for a value above 1000000 e.g. www.bolt.com/records?price=>1000000

### Expected result

Record created with value over 1000000 should be shown in list of results.

### Actual result

Nothing shows in results.

**Comment by harrigo** [comment]
Sure so this is the output. It returned stuff so unsure if I wrote my issue the wrong way around and less than returned nothing but regardless whatever it happening is unexpected at least for me, unsure if it thinks it is text or something and sorts fine when same number of digits and then breaks after.

SELECT content FROM Bolt\Entity\Content content LEFT JOIN content.fields fields_price LEFT JOIN fields_price.translations translations_price WHERE content.contentType = :ct0 AND ((translations_price.value > :price_1 AND fields_price.parent IS NULL AND fields_price.name = :field_price) AND content.status = :status_1) ORDER BY content.publishedAt DESC
ct0: properties
price_1: ["1000000"]
status_1: published
field_price: price

**Comment by I-Valchev** [comment]
Hi @harrigo , 

Unfortunately that's a limitation in Bolt 4, as you mention it's interpreting it as a string and giving you unexpected results.

This has already been fixed in Bolt 5, which is in the pipeline (beta releases are out already). I'd advise you to switch over to 5 if that bugfix is important for you 👍

**Comment by harrigo** [comment]
Thanks for the update! I was worried that may be the case.

I will give the bolt update a go pretty new to Bolt so bit confused by all
these versions in development. Hoping time on theme and extension won't be
wasted and comes across ok really!

**Comment by I-Valchev** [comment]
Sure! At the moment it can be a bit confusing, but in short: Bolt 4 is the current stable release. Bolt 5 will be the next stable release, once it is out. At the moment, we have beta versions released.

Feel free to join up our slack channel https://boltcms.io/community , I can help out some more there too.

**Comment by harrigo** [comment]
Brill yeah, have joined thatm, also got Bolt updated to **Bolt version5.0.0 β 8** my problem here still persists. Update couldn't of gone more smoothly however once I found instructions and my theme and module seem to work perfectly at first glance so hopefully it's just something small!

**Comment by harrigo** [comment]
Ok so have additional debugging for this... Believe this may be wrong as always errors for me:

https://github.com/bolt/core/blob/4.1/src/Doctrine/Version.php#L91

`->select('CAST (1.1 AS int)');`

should have no space between CAST and opening bracket:

`->select('CAST(1.1 AS int)');`

This is used around here to check if it is a numeric field:

https://github.com/bolt/core/pull/2635/files#diff-3506610ce919db13f0c867613c8cba94c6349ef0820faec47bda84649dfc47e2R601 

My ordering by numbers now seems to work however filtering does not. Only thing i can think is that the parametised value looks a bit off and is a json array the values in the database are substrings of the array offset by the square bracket quationation yet the parametised value still includes square brackets and quoatations and maybe it shouldn't:


```
SELECT content FROM Bolt\Entity\Content content LEFT JOIN content.fields fields_asking_price LEFT JOIN fields_asking_price.translations translations_asking_price LEFT JOIN content.fields fields_order_1 LEFT JOIN fields_order_1.translations translations_order_1 WHERE content.contentType = :ct0 AND ((CAST(SUBSTRING(translations_asking_price.value, 3, LENGTH(translations_asking_price.value)) as decimal) > :asking_price_1 AND fields_asking_price.parent IS NULL AND fields_asking_price.name = :field_asking_price) AND content.status = :status_1) AND fields_order_1.name = :order_1 ORDER BY CAST(SUBSTRING(translations_order_1.value, 3, LENGTH(translations_order_1.value)) as decimal) ASC
ct0: properties
asking_price_1: ["250000"]
status_1: published
field_asking_price: asking_price
order_1: asking_price
```

**Comment by bobdenotter** [comment]
Fixed in #2649
